### ISSUE TITLE
docker-compose up mysql-init 错误

### ISSUE THREAD

**Issue by qqqqqqq1995** [zhoutaoo/SpringCloud#103]
init-db.sh 为windows 格式导致 初始化错误

**Comment by zhoutaoo** [comment]
请贴错误

**Comment by yangtaoxf** [comment]
[root@localhost docker-compose]# docker-compose up mysql-init
Creating network "docker-compose_sc-net" with the default driver
Pulling mysql-init (mysql:5.7)...
5.7: Pulling from library/mysql
d599a449871e: Pull complete
f287049d3170: Pull complete
08947732a1b0: Pull complete
96f3056887f2: Pull complete
871f7f65f017: Pull complete
1dd50c4b99cb: Pull complete
5bcbdf508448: Pull complete
02a97db830bd: Pull complete
c09912a99bce: Pull complete
08a981fc6a89: Pull complete
818a84239152: Pull complete
Digest: sha256:5779c71a4730da36f013a23a437b5831198e68e634575f487d37a0639470e3a8
Status: Downloaded newer image for mysql:5.7
Creating docker-compose_mysql-init_1 ... done
Attaching to docker-compose_mysql-init_1
mysql-init_1  | /usr/local/bin/docker-entrypoint.sh: line 363: /init-db.sh: Permission denied
docker-compose_mysql-init_1 exited with code 126

**Comment by yangtaoxf** [comment]
mysql-init_1  | /usr/bin/env: 'bash\r': No such file or directory

**Comment by yangtaoxf** [comment]
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
[root@localhost docker-compose]# docker-compose -f docker-compose.monitor.yml  up -d
WARNING: Found orphan containers (sc-prometheus, sc-nacos-standalone, sc-rabbitmq, sc-mysql, sc-redis) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Pulling monitor-admin (cike/admin:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

**Comment by zhoutaoo** [comment]
> Configure a credential helper to remove this warning. See
> https://docs.docker.com/engine/reference/commandline/login/#credentials-store
> 
> Login Succeeded
> [root@localhost docker-compose]# docker-compose -f docker-compose.monitor.yml up -d
> WARNING: Found orphan containers (sc-prometheus, sc-nacos-standalone, sc-rabbitmq, sc-mysql, sc-redis) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
> Pulling monitor-admin (cike/admin:latest)...
> ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

如果你没执行过install.sh脚本的话，你需要手工打cike/admin:latest的docker image

**Comment by yangtaoxf** [comment]
明白了，谢谢
