### ISSUE TITLE
配置文件

### ISSUE THREAD

**Issue by meditational** [zhoutaoo/SpringCloud#104]
${DATASOURCE_HOST:localhost}这种写法不是很明白，可以解释一下吗，启动sysadmin这个服务一直是数据库一直是localhost,没有读取配置文件env配置中心的配置

**Comment by wenyangchou** [comment]
java -jar -DDATASOURCE_HOST=ip app.jar 。
如果DATASOURCE_HOST 参数不设置，则默认为localhost。
相当于三元表达式： DATASOURCE_HOST==null?localhost:DATASOURCE_HOST

**Comment by zhoutaoo** [comment]
> ${DATASOURCE_HOST:localhost}这种写法不是很明白，可以解释一下吗，启动sysadmin这个服务一直是数据库一直是localhost,没有读取配置文件env配置中心的配置

DATASOURCE_HOST这个是优先从环境 变量或java参数上读取，如果都没有值 取：后的默认值
