### ISSUE TITLE
maven install 出现异常

### ISSUE THREAD

**Issue by baiwq** [zhoutaoo/SpringCloud#105]
![image](https://user-images.githubusercontent.com/34566161/69395693-e7f31600-0d1a-11ea-977f-a188c4d7d59e.png)
走到这一步的时候，出现了下面的问题，请大佬解答
![image](https://user-images.githubusercontent.com/34566161/69395750-0b1dc580-0d1b-11ea-8ccb-bfb0cbf9b9a5.png)

**Comment by zhoutaoo** [comment]
包没下载下来，多试几次
