### ISSUE TITLE
authentication-server中的WebServerSecurityConfig配置项不生效

### ISSUE THREAD

**Issue by bwcxjason** [zhoutaoo/SpringCloud#106]
**BUG描述**

authentication-server中的WebServerSecurityConfig配置项不生效，当访问/actuator端点时提示没有访问权限。

**截图**
WebServerSecurityConfig配置类，此配置不生效：
![image](https://user-images.githubusercontent.com/15324452/69432961-acd20080-0d75-11ea-92b3-cf9b526d845b.png)

**原因**
由于ResourceServerConfig配置比WebServerSecurityConfig具有更高的优先级，所以它对HttpSecurity的配置会生效。本例中为ResourceServerConfig父类ResourceServerConfigurerAdapter的默认配置，如下所示：
![image](https://user-images.githubusercontent.com/15324452/69433284-4b5e6180-0d76-11ea-911a-19391c44d2f6.png)

**Comment by zhoutaoo** [comment]
已在dev分支处理好，之后合并master，这块之后还要重构
