### ISSUE TITLE
install.sh 运行至4.3构建镜像:消息中心路径有错

### ISSUE THREAD

**Issue by hahahanhan1122** [zhoutaoo/SpringCloud#109]
**install.sh 运行至”4.3构建镜像:消息中心“路径有错**

清晰的BUG描述，有助于判断问题，请按如下步骤

 1.说明操作的背景，使用了哪个模块什么功能？
  执行 install.sh 运行至”4.3构建镜像:消息中心“，执行“cd ./center/bus”找不到路径
 2.怎么输入或操作的得到了什么结果？
 ./install.sh
 3.预期结果与实际有什么差异？     
执行 install.sh后应所有应用启动成功

**Comment by wzfjesun** [comment]
我也报这个错，请问怎么解决？

**Comment by AAAaaa-1119** [comment]
修改
```

67   echo '==================4.3.构建镜像: 配置中心, 消息中心========'
68
69   #回到根目录
70   #cd -
```

**Comment by zhoutaoo** [comment]
已修复
