### ISSUE TITLE
认证服务端添加了接口，postman访问不到

### ISSUE THREAD

**Issue by qiushaopeng** [zhoutaoo/SpringCloud#111]
认证服务端添加了个新接口，postman请求发现接收不到，接口已经设置security不拦截了

**Comment by mytaia** [comment]
hello














------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"qiushaopeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月11日(星期三) 晚上7:03
收件人:&nbsp;"zhoutaoo/SpringCloud"<SpringCloud@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[zhoutaoo/SpringCloud] 认证服务端添加了接口，postman访问不到 (#111)




认证服务端添加了个新接口，postman请求发现接收不到，接口已经设置security不拦截了

**Comment by qiushaopeng** [comment]
？？这项目还维护么，今天刚看到，感觉东西挺多的

**Comment by zhoutaoo** [comment]
> ？？这项目还维护么，今天刚看到，感觉东西挺多的

维护，不过最近有点忙

**Comment by zhoutaoo** [comment]
> 认证服务端添加了个新接口，postman请求发现接收不到，接口已经设置security不拦截了

接收不到 原因很多

**Comment by qiushaopeng** [comment]
有微信群吗，二维码过期了，如果有还请分享下，还有不知道有没有办法参与下

**Comment by zhoutaoo** [comment]
二维码已更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"qiushaopeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月12日(星期四) 上午10:13
收件人:&nbsp;"zhoutaoo/SpringCloud"<SpringCloud@noreply.github.com&gt;;
抄送:&nbsp;"听风雨"<zhoutaoo@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zhoutaoo/SpringCloud] 认证服务端添加了接口，postman访问不到 (#111)




有微信群吗，二维码过期了，如果有还请分享下，还有不知道有没有办法参与下
