### ISSUE TITLE
authentication-client这个模块，mvn install一直downloading

### ISSUE THREAD

**Issue by kalvinGit** [zhoutaoo/SpringCloud#119]
**BUG描述**
在idea 使用mvn install命令安装authentication-client模块时，一直downloading直到超时：
`"C:\Program Files\Java\jdk-11\bin\java.exe" -Dmaven.multiModuleProjectDirectory=D:\Kalvin\ideaProjects\SpringCloud\auth\authentication-client "-Dmaven.home=D:\Program Files\JetBrains\IntelliJ IDEA 2019.1\plugins\maven\lib\maven3" "-Dclassworlds.conf=D:\Program Files\JetBrains\IntelliJ IDEA 2019.1\plugins\maven\lib\maven3\bin\m2.conf" "-Dmaven.ext.class.path=D:\Program Files\JetBrains\IntelliJ IDEA 2019.1\plugins\maven\lib\maven-event-listener.jar" "-javaagent:D:\Program Files\JetBrains\IntelliJ IDEA 2019.1\lib\idea_rt.jar=57610:D:\Program Files\JetBrains\IntelliJ IDEA 2019.1\bin" -Dfile.encoding=UTF-8 -classpath "D:\Program Files\JetBrains\IntelliJ IDEA 2019.1\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar" org.codehaus.classworlds.Launcher -Didea.version2019.2.2 install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.springboot.cloud:authentication-client:jar:0.0.1-SNAPSHOT
[WARNING] 'dependencies.dependency.version' for org.projectlombok:lombok:jar is either LATEST or RELEASE (both of them are being deprecated) @ line 61, column 22
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] -------------< com.springboot.cloud:authentication-client >-------------
[INFO] Building authentication-client 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from spring-milestones: http://maven.aliyun.com/nexus/content/groups/public/io/netty/netty-transport-native-epoll/4.1.24.Final/netty-transport-native-epoll-4.1.24.Final.jar
`
 

**环境**
jdk11
操作系统、组件版本、数据库等
window
mysql

**Comment by zhoutaoo** [comment]
请加快网络，或者 换中央仓库
