### ISSUE TITLE
Could not autowire. There is more than one bean of 'Validator' type.

### ISSUE THREAD

**Issue by ustcwudi** [zhoutaoo/SpringCloud#13]
IDEA inspection report an error: "public class DefaultRedisRateLimiter extends RedisRateLimiter"

Could not autowire. There is more than one bean of 'Validator' type.
Beans:
defaultValidator   (ValidationAutoConfiguration.class) 
webFluxValidator   (WebFluxConfigurationSupport.class)

**Comment by zhoutaoo** [comment]
已处理
