### ISSUE TITLE
organization项目必须比authentication-server先启动的问题

### ISSUE THREAD

**Issue by acehjr** [zhoutaoo/SpringCloud#130]
如果authentication-server先启动，其ResourceService类的resourceConfigAttributes就会无值，导致整个项目权限校验都用不了。

**Comment by Hyperion-v** [comment]
加个判断吧,当resourceConfigAttributes为空的时候重新load一次,不过这确实是个问题

**Comment by mistxzh** [comment]
不错，不错，解决了，感谢。

**Comment by zhoutaoo** [comment]
加载资源失败时，启动失败
