### ISSUE TITLE
平台搭建完成 默认用户名密码无法登陆 显示404

### ISSUE THREAD

**Issue by 76373310** [zhoutaoo/SpringCloud#133]
**BUG描述**

清晰的BUG描述，有助于判断问题，请按如下步骤

 1.说明操作的背景，使用了哪个模块什么功能？
  
 2.怎么输入或操作的得到了什么结果？
 
 3.预期结果与实际有什么差异？     

**截图**
![image](https://user-images.githubusercontent.com/14249479/76843406-b3c9d500-6876-11ea-8dd5-7475735b1172.png)

**环境**

操作系统、组件版本、数据库等

**Comment by zhoutaoo** [comment]
https://github.com/zhoutaoo/SpringCloud/wiki/常见问题#启动前端项目后请求报404


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"seedWang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月17日(星期二) 下午5:43
收件人:&nbsp;"zhoutaoo/SpringCloud"<SpringCloud@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[zhoutaoo/SpringCloud] 平台搭建完成 默认用户名密码无法登陆 显示404 (#133)





 
BUG描述
 
清晰的BUG描述，有助于判断问题，请按如下步骤
 
1.说明操作的背景，使用了哪个模块什么功能？
 
2.怎么输入或操作的得到了什么结果？
 
3.预期结果与实际有什么差异？
 
截图
 
 
环境
 
操作系统、组件版本、数据库等

**Comment by 76373310** [comment]
![image](https://user-images.githubusercontent.com/14249479/76904634-5451e080-68db-11ea-8a34-f745ed3d14c7.png)
 请问是否可以加个微信联系 15210957149

**Comment by zhoutaoo** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"seedWang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月18日(星期三) 上午8:36
收件人:&nbsp;"zhoutaoo/SpringCloud"<SpringCloud@noreply.github.com&gt;;
抄送:&nbsp;"听风雨"<zhoutaoo@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zhoutaoo/SpringCloud] 平台搭建完成 默认用户名密码无法登陆 显示404 (#133)





 
Closed #133.
