### ISSUE TITLE
返回401

### ISSUE THREAD

**Issue by lishangpeng** [zhoutaoo/SpringCloud#134]
**BUG描述**

清晰的BUG描述，有助于判断问题，请按如下步骤

 1.说明操作的背景，使用了哪个模块什么功能？
使用了auth 和 geteway
  
 2.怎么输入或操作的得到了什么结果？

 
![image](https://user-images.githubusercontent.com/26132566/77938027-ba7d3100-72e7-11ea-8731-e69660c1809a.png)

![image](https://user-images.githubusercontent.com/26132566/77938047-c0731200-72e7-11ea-9d5c-32e11f5dd9ed.png)

![image](https://user-images.githubusercontent.com/26132566/77938063-c668f300-72e7-11ea-9d9b-bec908deedd4.png)

 3.预期结果与实际有什么差异？     
按文档的操作 本应该返回token 现在返回错误信息
**截图**
![image](https://user-images.githubusercontent.com/26132566/77938225-029c5380-72e8-11ea-946f-f4a65be2a7cc.png)
![image](https://user-images.githubusercontent.com/26132566/77938250-0cbe5200-72e8-11ea-9ebb-60de0c0ab0a2.png)

**环境**

操作系统、组件版本、数据库等

**Comment by Hyperion-v** [comment]
auth-clint是否install?

**Comment by lishangpeng** [comment]
> auth-clint是否install?

![image](https://user-images.githubusercontent.com/26132566/78155365-f0e5b800-746f-11ea-9ed7-f36a8e067c89.png)
你好 已经installguo'l过啦

**Comment by lishangpeng** [comment]
![image](https://user-images.githubusercontent.com/26132566/78157312-66528800-7472-11ea-9e74-e9a2b1d8c97e.png)
