### ISSUE TITLE
怎么初始化网关服务的DB？

### ISSUE THREAD

**Issue by onexuan** [zhoutaoo/SpringCloud#140]
怎么初始化网关服务的DB:./gateway/gateway-admin/src/main/db？

**Comment by zhoutaoo** [comment]
是




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fonter.yang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 下午5:19
收件人:&nbsp;"zhoutaoo/SpringCloud"<SpringCloud@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[zhoutaoo/SpringCloud] 怎么初始化网关服务的DB？ (#140)





 
怎么初始化网关服务的DB:./gateway/gateway-admin/src/main/db？

**Comment by onexuan** [comment]
回复“是”根本解决不了问题

**Comment by zhijiezung** [comment]
是的。

**Comment by zhijiezung** [comment]
是的。
