### ISSUE TITLE
docker-compose文件  networks的问题

### ISSUE THREAD

**Issue by nicexy** [zhoutaoo/SpringCloud#141]
请问 docker-compose.yml文件中的 external: false 
目前先启动docker-compose.yml 在启动nacos会报找不到sc-net的错  
改true create后 报另外一个错  有遇到的吗  没搞过docker

**Comment by zhoutaoo** [comment]
https://github.com/zhoutaoo/SpringCloud/tree/master/docker-compose#%E5%90%AF%E5%8A%A8%E9%98%BF%E9%87%8C%E6%B3%A8%E5%86%8C%E4%B8%AD%E5%BF%83%E5%92%8C%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83nacos
请按文档启动命令来操作
