### ISSUE TITLE
authetication鉴权服务

### ISSUE THREAD

**Issue by Xfj0911** [zhoutaoo/SpringCloud#142]
**BUG描述**

清晰的BUG描述，有助于判断问题，请按如下步骤

 1.说明操作的背景，使用了哪个模块什么功能？
     postman测试下authication-server模块

 2.怎么输入或操作的得到了什么结果？
     请求：http://localhost:8443/authorization-server/oauth/token获取access_token, 然后携带token访问http://localhost:8443/organization/user/101 失败：Unauthorized
     此为：通过网管调用资源服务，在鉴权的时候的返回

 3.预期结果与实际有什么差异？     
     预期结果：成功，并获取到用户信息
**截图**
![image](https://user-images.githubusercontent.com/50622110/81548972-a4679380-93b0-11ea-87b0-38d27e84eb23.png)

本人试了下：修改
![image](https://user-images.githubusercontent.com/50622110/81549198-f0b2d380-93b0-11ea-8742-8327df0c41e9.png)
或redis存储。。。。 可以正常返回数据
![image](https://user-images.githubusercontent.com/50622110/81549282-0e803880-93b1-11ea-9d7b-3971ee502334.png)

烦请补充下此问题，和微服务之间openfeign相互调用，并且微服务资源接口，如何做限制（防止直接调用为微服务端口进行访问资源）
**环境**
   初始环境

**Comment by zhoutaoo** [comment]
beartoken在传背时格式为 Bearer {{access_token}}
