### ISSUE TITLE
Feign切换到OkHttpClient是否无效？

### ISSUE THREAD

**Issue by kalvinGit** [zhoutaoo/SpringCloud#146]
**BUG描述**

在项目中FeignOkHttpConfig配置了自定义拦截器（拦截器只是简单输出下调用日志），
调用授权接口并没有执行自定义拦截器。
我又尝试下debug了OkHttp3的源码中的RealCall类的execute()和enqueue()方法。也是调用授权接口，然而并没有进入预期的断点。

**截图**
附上自定义拦截器代码截图
![image](https://user-images.githubusercontent.com/34390593/83491590-96ef8600-a4e4-11ea-9d3f-277b0032ac71.png)

**环境**

window10、mysql8、使用idea运行

**Comment by zhoutaoo** [comment]
拦截器有加入 调用链中吗？
![image](https://user-images.githubusercontent.com/3946731/83943379-11464000-a82e-11ea-945d-1822b9288c83.png)

**Comment by kalvinGit** [comment]
对，已经加入了
