### ISSUE TITLE
找了半天登陆的控制器都没找到啊，大佬是没提交吗？

### ISSUE THREAD

**Issue by xiaolegehaha** [zhoutaoo/SpringCloud#147]
**BUG描述**
我刚拿到代码，想要首先从登录入口进行代码跟踪学习，结果

POST /oauth/token?grant_type=authorization_code&code=A32sYi&redirect_uri=http://baidu.com HTTP/1.1
Host: localhost:8000
Authorization: Basic dGVzdF9jbGllbnQ6dGVzdF9zZWNyZXQ=
Cache-Control: no-cache

你这个负责登陆的控制器在代码里面没找到啊，还有token刷新的相关代码也没找到，还有网关路由刷新那里好像也少了代码，只看到了缓存路由信息但是没看到publisher。

新手求指点啊

**Comment by shineabel** [comment]
这是框架的代码

**Comment by gaofrank** [comment]
收到！
