### ISSUE TITLE
二维码过期 帮忙拉进群

### ISSUE THREAD

**Issue by iot-hunter** [zhoutaoo/SpringCloud#157]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tonkong** [comment]
me too

**Comment by 7omsxx** [comment]
是否可以开个qq群，人可以多点

**Comment by hhhhax** [comment]
me too

**Comment by Xiaoshenshe** [comment]
me too

**Comment by liming2020** [comment]
me too

**Comment by zhoutaoo** [comment]
![0C92395B-179C-4E09-BDE6-9F93EF42316A](https://user-images.githubusercontent.com/3946731/90701723-f11a0f00-e2bb-11ea-88ef-de052ac12cd0.jpeg)

**Comment by iot-hunter** [comment]
二维码过期了  我又错过了 可否再分享下@zhoutaoo

**Comment by liming2020** [comment]
> 二维码过期了我又错过了可否再分享下@zhoutaoo

![微信图片_20200827215325](https://user-images.githubusercontent.com/46783367/91451197-c2013000-e8af-11ea-87a7-9a969478b873.jpg)

**Comment by qierkang** [comment]
二维码过期了我又错过了可否再分享下@zhoutao

**Comment by liming2020** [comment]
> 二维码过期了我又错过了可否再分享下@zhoutao
![Screenshot_20200906_195026_com tencent mm](https://user-images.githubusercontent.com/46783367/92325102-810cd680-f07a-11ea-8ed1-5f92afb0b955.jpg)

**Comment by ZoeC5** [comment]
又过期了,可以麻烦再发下吗?
