### ISSUE TITLE
建议为不用docker的用户写一个使用手册

### ISSUE THREAD

**Issue by d15801543974** [zhoutaoo/SpringCloud#167]
因为mysql redis rabbitmq elasticsearch等，好多人都是单独安装的，对于没有接触过docker但是这个基础服务都懂的人不太友好。毕竟到了生产环境用docker的人好少。本人就是这种情况

其实也不用写太复杂，简单的yml配置mysql和Redis就行
还有就是启动顺序的问题

谢谢

**Comment by DirZhang** [comment]
不会用docker 玩什么微服务啊

**Comment by d15801543974** [comment]
> 不会用docker玩什么微服务啊

微服务必须依赖docker？ 开什么玩笑
