### ISSUE TITLE
nacos中心动态配置问题

### ISSUE THREAD

**Issue by wonderpan** [zhoutaoo/SpringCloud#181]
gateway-web启动后能正常获取到配置，但是配置修改后未刷新，所有项目都启动了，在nacos中也能看到节点信息

**Comment by invlong** [comment]
> gateway-web启动后能正常获取到配置，但是配置修改后未刷新，所有项目都启动了，在nacos中也能看到节点信息

这个需要自己实现

**Comment by hello007** [comment]
可参考@RefreshScope（需引入spring-cloud-starter-config）
