### ISSUE TITLE
为什么获取不到Greenwich.RELEASE的依赖

### ISSUE THREAD

**Issue by dxy9** [zhoutaoo/SpringCloud#31]
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Greenwich.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

pom文件中提示：
Dependency 'org.springframework.cloud:spring-cloud-dependencies:Greenwich.RELEASE' not found

**Comment by zhoutaoo** [comment]
请检查你的maven仓库的配置或私有库与中央仓库同步情况
