### ISSUE TITLE
authentication-server新增权限url需要重启服务才能生效

### ISSUE THREAD

**Issue by XvYong** [zhoutaoo/SpringCloud#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhoutaoo** [comment]
方案：
通过MQ将资源权限变更推送到各运行中的授权节点
1. 在变更资源时时触发MQ事件，将资源信息写入MQ中
2. 授权应用监听MQ资源变更事件，将变更的资源写入configAttributes中
注：资源变更并授与某角色后，用户需要重新获取token才能获得新资源的权限

**Comment by zhoutaoo** [comment]
用户token目前包含角色code，后台拿到token后根据用户id查询到用户拥有的所有角色，再根据角色id查询到所有的权限集合。

**Comment by TshineZheng** [comment]
这个问题何时安排解决，重启服务也无效，因为取的是缓存。

**Comment by zhoutaoo** [comment]
已经处理好了
