### ISSUE TITLE
[用户]没有[角色]时, SQL会执行错误. 

### ISSUE THREAD

**Issue by imyzt** [zhoutaoo/SpringCloud#36]
**BUG描述**

 1.说明操作的背景，使用了哪个模块什么功能？

将默认的postgresql修改为mysql.   

编写了一个子业务模块, 通过网关鉴权, 在解析JWT之后, 通过用户获取角色, 通过角色获取资源信息时, 如果用户角色为空, 将会`@Select`的SQL语句会执行出错. 因为后续的`foreach`没有执行.   

 2.怎么输入或操作的得到了什么结果？

用户没有角色信息时, 鉴权时出现SQL异常.   

 3.预期结果与实际有什么差异？     

预期结果应该是做非空判断, 避免此异常.  

**截图**

![角色为空](https://user-images.githubusercontent.com/28680198/57992610-abcec680-7ae7-11e9-9d20-9dcab3ef4e83.jpg)
![异常堆栈信息](https://user-images.githubusercontent.com/28680198/57992611-ac675d00-7ae7-11e9-87ef-96bfe5d7a6b3.jpg)

[authentication.log](https://github.com/zhoutaoo/SpringCloud/files/3196032/authentication.log)

**环境**

win10  
java8
MySQL

**Comment by zhoutaoo** [comment]
ok，后期会改为通过userid后台查询角色，不使用token中记录

**Comment by zhoutaoo** [comment]
改为通过userid后台查询角色
