### ISSUE TITLE
MD文档描述有误

### ISSUE THREAD

**Issue by wuyongdec** [zhoutaoo/SpringCloud#42]
在auth模块的readme.md里面提到：
`
#### 本例中Spring OAuth2中Token结构简介
| token_type   | Bearer和OAuth2  
`
参考oauth2规范文档
[https://tools.ietf.org/html/rfc6749#section-7.1](https://tools.ietf.org/html/rfc6749#section-7.1)
应该是Bearer和Mac

**Comment by zhoutaoo** [comment]
已处理
