### ISSUE TITLE
授权服务和认证服务，在admin模块上, 显示不了服务的信息，授权服务和认证服务日志显示需要认证

### ISSUE THREAD

**Issue by feng-dan** [zhoutaoo/SpringCloud#43]
**BUG描述**

清晰的BUG描述，有助于判断问题，请按如下步骤

 1.说明操作的背景，使用了哪个模块什么功能？
      使用了 授权服务和认证服务,eureka服务，admin模块，网关web服务
 2.怎么输入或操作的得到了什么结果？
     在admin服务上查看不到，授权服务和认证服务 的信息，网关web服务，可以查看
 3.预期结果与实际有什么差异？     
     授权服务和认证服务 日志输入需要认证授权
**截图**
![image](https://user-images.githubusercontent.com/29519215/58793079-fabc4600-8627-11e9-8b8a-2cf9c4a80536.png)
![image](https://user-images.githubusercontent.com/29519215/58793252-5555a200-8628-11e9-83e9-5f54f2e950aa.png)

**环境**

操作系统、组件版本、数据库等
Windows10     
Mysql               5.7
spring-boot     2.0.9.RELEASE 
spirng-cloud    Finchley.RELEASE
spring-boot-admin-starter-server   2.0.3

**Comment by zhoutaoo** [comment]
本项目已升级到 了Greenwich.RELEASE  
spring-boot 2.1.4.RELEASE

**Comment by zhoutaoo** [comment]
另外描述问题请描述清楚，是启动就报异常，还是请求了什么地址报错 @feng-dan

**Comment by feng-dan** [comment]
项目版本 我准备不升级到2.1

**Comment by zhoutaoo** [comment]
非该项目问题，关闭issues
