### ISSUE TITLE
elasticsearch:alpine无此镜像

### ISSUE THREAD

**Issue by jianhaifeng** [zhoutaoo/SpringCloud#49]
**BUG描述**

清晰的BUG描述，有助于判断问题，请按如下步骤

 1.说明操作的背景，使用了哪个模块什么功能？
  
 2.怎么输入或操作的得到了什么结果？
 
 3.预期结果与实际有什么差异？     

**截图**

**环境**

操作系统、组件版本、数据库等

**Comment by zhoutaoo** [comment]
可以使用阿里docker镜像就行

**Comment by zhoutaoo** [comment]
已更换官方源elasticsearch:5.6-alpine
