### ISSUE TITLE
集成Spring Cloud Alibaba Nacos注册中心

### ISSUE THREAD

**Issue by zhoutaoo** [zhoutaoo/SpringCloud#53]
Eureka其 2.0 版本的开源工作已经停止，故换Spring Cloud Alibaba Nacos为注册中心

**Comment by Jiiiiiin** [comment]
:)

**Comment by jsxiao** [comment]
> Eureka其 2.0 版本的开源工作已经停止，故换Spring Cloud Alibaba Nacos为注册中心

spring cloud 集成的是eureka1.x版本，2.x版本一直没有发布稳定版，所以不必惊慌。你可以去官网看看，而且spring cloud greenwich版本集成的是 1.9.x版本的eureka。

**Comment by lyings** [comment]
可以替换  apollo了。

**Comment by zhoutaoo** [comment]
> 可以替换 apollo了。

这个也在考虑，可以少引入一个开源组件

**Comment by lyings** [comment]
能否问你一个服务管理的问题。就是在多人员参与的项目中。比如这些基本服务我不想让其他成员读写源代码，或者A服务开发的人员不能读写B服务开发人员的代码。请问你们是怎么管理的。？？能qq联系一下吗？QQ：123938248

**Comment by zhoutaoo** [comment]
> 能否问你一个服务管理的问题。就是在多人员参与的项目中。比如这些基本服务我不想让其他成员读写源代码，或者A服务开发的人员不能读写B服务开发人员的代码。请问你们是怎么管理的。？？能qq联系一下吗？QQ：123938248

https://github.com/zhoutaoo/SpringCloud/wiki 可以入群讨论
