### ISSUE TITLE
二维码已经过期~~

### ISSUE THREAD

**Issue by Jiiiiiin** [zhoutaoo/SpringCloud#58]
我们也在做类似的事情，想交流学习一下，方便更新一下交流群二维码不？

**Comment by zhoutaoo** [comment]
------------------ 原始邮件 ------------------
发件人: "赵津"<notifications@github.com>;
发送时间: 2019年8月6日(星期二) 中午11:09
收件人: "zhoutaoo/SpringCloud"<SpringCloud@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [zhoutaoo/SpringCloud] 二维码已经过期~~ (#58)




我们也在做类似的事情，想交流学习一下，方便更新一下交流群二维码不？

**Comment by zhoutaoo** [comment]
![image](https://user-images.githubusercontent.com/3946731/62508721-39929600-b83b-11e9-84b9-2f3e191ecd16.png)
