### ISSUE TITLE
微信群二维码过期了

### ISSUE THREAD

**Issue by jsxiao** [zhoutaoo/SpringCloud#59]
8月5日就过期了。。。 微信6群的二维码

**Comment by zhoutaoo** [comment]
新建了个群
![wechat](https://user-images.githubusercontent.com/3946731/62678253-93ce5b00-b9e3-11e9-8444-9fe3d2368abe.jpg)

**Comment by zhoutaoo** [comment]
![微信图片_20190816170031](https://user-images.githubusercontent.com/3946731/63156587-96fec200-c047-11e9-86ee-2a1e01206521.jpg)

**Comment by zhoutaoo** [comment]
![微信图片_20190827095554](https://user-images.githubusercontent.com/3946731/63735083-31190280-c8b1-11e9-9da3-a1f7da231cb4.jpg)

**Comment by zhoutaoo** [comment]
![微信图片_20190830095433](https://user-images.githubusercontent.com/3946731/63987984-bba96e00-cb0c-11e9-9838-29af642c95f2.jpg)
