### ISSUE TITLE
执行install.sh后，rabbitmq 没有监听5672端口， redis没有监听6379端口

### ISSUE THREAD

**Issue by HenryZhouHB** [zhoutaoo/SpringCloud#69]
**BUG描述**
执行install.sh后，rabbitmq 没有监听5672端口， redis没有监听6379端口

[root@localhost ~]# docker ps -a
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                          PORTS                    NAMES
99cd4b5e0a5c        cike/admin:latest                   "java -jar /app.jar"     5 minutes ago       Up 5 minutes                    0.0.0.0:8022->8022/tcp   sc-monitor-admin
f91b6c2e961f        cike/authorization-server:latest    "java -jar /app.jar"     6 minutes ago       Up 6 minutes                    0.0.0.0:8000->8000/tcp   sc-authorization-server
29a3059919b4        cike/authentication-server:latest   "java -jar /app.jar"     6 minutes ago       Up 5 minutes                    0.0.0.0:8001->8001/tcp   sc-authentication-server
ac5cc3f5ce1a        cike/organization:latest            "java -jar /app.jar"     14 minutes ago      Up 14 minutes                   0.0.0.0:8010->8010/tcp   sc-organization
e7f6768f17a1        cike/gateway-admin:latest           "java -jar /app.jar"     17 minutes ago      Up 17 minutes                   0.0.0.0:8445->8445/tcp   sc-gateway-admin
9765bd7ee33d        cike/gateway-web:latest             "java -jar /app.jar"     17 minutes ago      Up 17 minutes                   0.0.0.0:8443->8443/tcp   sc-gateway-web
5c88816c3d9a        cike/config-server:latest           "java -jar /app.jar"     41 minutes ago      Up 41 minutes                   0.0.0.0:8888->8888/tcp   sc-config
2c48dd0c3153        cike/eureka-server:latest           "java -jar /app.jar"     41 minutes ago      Up 41 minutes                   0.0.0.0:8761->8761/tcp   sc-eureka
09ca6967771e        rabbitmq:alpine                     "docker-entrypoint..."   43 minutes ago      Restarting (1) 15 minutes ago                            sc-rabbitmq
992218c043b7        redis:alpine                        "docker-entrypoint..."   43 minutes ago      Restarting (1) 15 minutes ago                            sc-redis
2fb7771cdee7        postgres:9.6-alpine                 "docker-entrypoint..."   43 minutes ago      Up 43 minutes                   0.0.0.0:5432->5432/tcp   sc-postgres
[root@localhost ~]# netstat -anp | more
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1527/master
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1249/sshd
tcp        0      0 192.168.1.80:22         192.168.1.136:51008     ESTABLISHED 1780/sshd: root@pts
tcp        0      0 192.168.1.80:22         192.168.1.136:53205     ESTABLISHED 61067/sshd: root@pt
tcp6       0      0 :::8761                 :::*                    LISTEN      66659/docker-proxy-
tcp6       0      0 ::1:25                  :::*                    LISTEN      1527/master
tcp6       0      0 :::8443                 :::*                    LISTEN      68727/docker-proxy-
tcp6       0      0 :::8445                 :::*                    LISTEN      68826/docker-proxy-
tcp6       0      0 :::8000                 :::*                    LISTEN      70320/docker-proxy-
tcp6       0      0 :::8001                 :::*                    LISTEN      70800/docker-proxy-
tcp6       0      0 :::8010                 :::*                    LISTEN      69439/docker-proxy-
tcp6       0      0 :::8022                 :::*                    LISTEN      70566/docker-proxy-
tcp6       0      0 :::22                   :::*                    LISTEN      1249/sshd
tcp6       0      0 :::8888                 :::*                    LISTEN      66760/docker-proxy-
tcp6       0      0 :::5432                 :::*                    LISTEN      63888/docker-proxy-
udp        0      0 0.0.0.0:68              0.0.0.0:*                           1051/dhclient
udp        0      0 127.0.0.1:323           0.0.0.0:*                           791/chronyd
udp6       0      0 ::1:323                 :::*                                791/chronyd
raw6       0      0 :::58                   :::*                    7           826/NetworkManager

操作系统、组件版本、数据库等

**Comment by zhoutaoo** [comment]
看一下
09ca6967771e rabbitmq:alpine "docker-entrypoint..." 43 minutes ago Restarting (1) 15 minutes ago sc-rabbitmq
992218c043b7 redis:alpine "docker-entrypoint..." 43 minutes ago Restarting (1) 15 minutes ago sc-redis
这两个容器报错日志

**Comment by HenryZhouHB** [comment]
[root@localhost SpringCloud]# docker logs b1863e024f6a
chown: /var/lib/rabbitmq/mnesia: Permission denied
chown: /var/lib/rabbitmq/mnesia/.gitkeep: Permission denied
chown: /var/lib/rabbitmq/mnesia: Permission denied
chown: /var/lib/rabbitmq/mnesia/.gitkeep: Permission denied
chown: /var/lib/rabbitmq/mnesia: Permission denied
chown: /var/lib/rabbitmq/mnesia/.gitkeep: Permission denied
chown: /var/lib/rabbitmq/mnesia: Permission denied
chown: /var/lib/rabbitmq/mnesia/.gitkeep: Permission denied
chown: /var/lib/rabbitmq/mnesia: Permission denied
chown: /var/lib/rabbitmq/mnesia/.gitkeep: Permission denied

[root@localhost SpringCloud]# docker logs df4a1d631300
chown: .: Permission denied
chown: ./.gitkeep: Permission denied
chown: .: Permission denied
chown: ./.gitkeep: Permission denied
chown: .: Permission denied
chown: ./.gitkeep: Permission denied
chown: .: Permission denied
chown: ./.gitkeep: Permission denied
chown: .: Permission denied
chown: ./.gitkeep: Permission denied

**Comment by zhoutaoo** [comment]
data目录的权限不够，修改一下权限就可以了

**Comment by HenryZhouHB** [comment]
data目录有权限啊
[root@localhost SpringCloud]# ls -l data
总用量 0
drwxrwxrwx. 3 root root 18 8月  17 17:05 config-server
drwxrwxrwx. 2 root root 22 8月  16 12:10 kong
drwxrwxrwx. 2 root root 22 8月  16 12:10 mysql
drwxrwxrwx. 3 root root 34 8月  16 14:56 postgres
drwxrwxrwx. 2 root root 22 8月  16 12:10 rabbitmq
drwxrwxrwx. 2 root root 22 8月  16 12:10 redis
[root@localhost SpringCloud]# ls -l
总用量 72
drwxrwxrwx. 6 root root   134 8月  16 12:10 auth
drwxrwxrwx. 5 root root    60 8月  16 12:10 center
drwxrwxrwx. 5 root root    56 8月  16 12:10 common
drwxrwxrwx. 8 root root    97 8月  17 17:05 data

**Comment by HenryZhouHB** [comment]
您指的是哪个data目录啊

**Comment by zhoutaoo** [comment]
drwxrwxrwx. 2 root root 22 8月 16 12:10 rabbitmq
drwxrwxrwx. 2 root root 22 8月 16 12:10 redis
这两个目录不能写得文件，你看下为啥不成写吧

**Comment by HenryZhouHB** [comment]
权限已经是777了，有权限的啊，而且我在这两个目录下手动创建文件可以成功，我的操作系统是cent-os7

**Comment by zhoutaoo** [comment]
看报错是执行chown: .: Permission denied时没有权限
你用root账号当然可以创建文件了。看一下 docker是哪个账号运行的？改一下属主吧

**Comment by HenryZhouHB** [comment]
docker是用root账号运行的，而且install.sh也是用root账号运行的

**Comment by HenryZhouHB** [comment]
你好，具体要怎么解决啊

**Comment by zhoutaoo** [comment]
https://www.cnblogs.com/YDDMAX/p/6184100.html请参考

**Comment by HenryZhouHB** [comment]
感谢，根据您提供的攻略，关闭 SELinux后，可以正常启动rabbitmq 和 redis，问题解决。
