### ISSUE TITLE
执行install.sh的过程中报错 ERROR: No such service: bud-server

### ISSUE THREAD

**Issue by HenryZhouHB** [zhoutaoo/SpringCloud#70]
**BUG描述**
执行install.sh的过程中报错 ERROR: No such service: bud-server

==================4.4.启动注册中心, 配置中心, 消息中心============
Creating sc-eureka ... done
Creating sc-config ... done
ERROR: No such service: bud-server
/opt/zhoutaoo/SpringCloud

**Comment by zhoutaoo** [comment]
dev已修复

**Comment by zhoutaoo** [comment]
dev已合并 到 master
