### ISSUE TITLE
data 下面没有数据文件 例如 MySQL  等等

### ISSUE THREAD

**Issue by sinolbs** [zhoutaoo/SpringCloud#77]
**BUG描述**

清晰的BUG描述，有助于判断问题，请按如下步骤

 1.说明操作的背景，使用了哪个模块什么功能？
  
 2.怎么输入或操作的得到了什么结果？
 
 3.预期结果与实际有什么差异？     

**截图**

**环境**

操作系统、组件版本、数据库等

**Comment by zhoutaoo** [comment]
运行mysql才有生成文件，请按文档操作
