### ISSUE TITLE
二维码已过期，请更换

### ISSUE THREAD

**Issue by JamesLiAndroid** [zhoutaoo/SpringCloud#78]
二维码已过期，请更换

请求增加不使用docker启动的步骤描述

**Comment by zhoutaoo** [comment]
![WechatIMG261](https://user-images.githubusercontent.com/3946731/64429309-3fa0be80-d0e8-11e9-9df8-0cf6dbdf7544.jpeg)

**Comment by zhoutaoo** [comment]
只有如下服务使用docker搭建，你可以自己在网上找教程搭建，比如 mysql什么的
![image](https://user-images.githubusercontent.com/3946731/64429431-9a3a1a80-d0e8-11e9-9219-98eac678d2c1.png)

**Comment by zhoutaoo** [comment]
![微信图片_20190916115314](https://user-images.githubusercontent.com/3946731/64933598-9a6caf80-d878-11e9-9f7a-3cf0459218b1.jpg)
