### ISSUE TITLE
token获取用户信息

### ISSUE THREAD

**Issue by wenyangchou** [zhoutaoo/SpringCloud#93]
认证授权时，获得token。那么调用 /user?uniqueId= 的接口，即使token所属的uniqueId不一致也可以获取。相当于用户与用户直接的信息可以相互看到

**Comment by zhoutaoo** [comment]
这个接口是根据用户唯一 id 查询用户信息，只该token有 /user?uniqueId=？的权限 就可以查询到，场景 比如，用户登陆时，根据用户名查询 用户账号信息

**Comment by wenyangchou** [comment]
我觉得这个接口不应该主动调用，而是后台通过解析token获得uniqueId

**Comment by zhoutaoo** [comment]
> 我觉得这个接口不应该主动调用，而是后台通过解析token获得uniqueId

登陆的时候 没有token ，同学
